alias    ...='cd ../..'
alias   ....='cd ../../..'
alias  .....='cd ../../../..'
alias ......='cd ../../../../..'

alias e='emacsclient -n'

alias g=git
alias ga='git add'
alias gaa='git add --all'
alias gb='git branch'
alias gcl='git clone'
alias gcld='git clone --depth=1'
alias gcm='git checkout master'
alias gcmsg='git commit -m'
alias gco='git checkout'
alias gd='git diff'
alias gf='git fetch'
alias gfa='git fetch --all'
alias gl='git pull'
alias glol='git lol'
alias glola='git lola'
alias gp='git push'
alias grb='git rebase'
alias grv='git remote -v'
alias gs='git status'
alias l='ls -lah'
alias la='ls -lAh'
alias lg='ls -la | grep -E'
alias ll='ls -lh'
alias ls='ls --color=auto'
alias p=popd
alias pg='ps aux | grep -E'
